<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Wire [
    <!ELEMENT Wire ANY>
    <!ELEMENT Colour (#PCDATA)>
    <!ELEMENT Length (Qty, Unit)>
    <!ELEMENT Qty ANY>
    <!ELEMENT Unit ANY>
]>
<Wire>
    <Colour>Red</Colour>
    <Length>
        <Qty>5</Qty>
        <Unit>Inches</Unit>
    </Length>
</Wire>